image: Visual Studio 2017

version: 1.0.{build}

branches:
  only:
  - master

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./Planer/Planer.csproj --verbosity m

build:
  project: Planer/Planer.csproj
  verbosity: minimal

test_script:
  - cmd: dotnet restore ./PlanerTests/PlanerTests.csproj --verbosity m
  - cmd: cd PlanerTests
  - cmd: dotnet test

deploy: off
