image: Visual Studio 2017

version: 1.0.{build}

branches:
  only:
  - master

build:
  project: Planer/Planer.csproj
  verbosity: detailed

test_script:
  - cmd: dotnet restore ./PlanerTests/PlanerTests.csproj --verbosity m
  - cmd: cd PlanerTests
  - cmd: dotnet test
